#!/usr/bin/env bash
# Instructions to check workflow in n8n UI
# Usage: bash scripts/check_workflow_in_ui.sh

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

echo "=========================================="
echo "Checking Workflow in n8n UI"
echo "=========================================="
echo ""
echo "The workflow execution completes in ~14ms with no data,"
echo "which suggests the workflow isn't actually running nodes."
echo ""
echo "To diagnose this, please:"
echo ""
echo "1. Open n8n UI in your browser:"
echo "   http://localhost:5678"
echo "   (Make sure SSH port forwarding is active)"
echo ""
echo "2. Navigate to: Workflows → 'AI Virtual Classroom - Five Teacher Workflow'"
echo ""
echo "3. Click on the 'Executions' tab (top of the workflow editor)"
echo ""
echo "4. Click on the most recent execution (ID 24 or latest)"
echo ""
echo "5. Check:"
echo "   - Which nodes executed (green = success, red = error)"
echo "   - What error messages appear (if any)"
echo "   - If the 'Select Teacher (Round-Robin)' node has any errors"
echo ""
echo "6. Also check the workflow itself:"
echo "   - Open the 'Select Teacher (Round-Robin)' code node"
echo "   - Verify the JavaScript code is correct"
echo "   - Check if there are any syntax errors"
echo ""
echo "Common issues:"
echo "  - Code node syntax errors"
echo "  - Missing input data"
echo "  - Workflow not properly connected"
echo ""
echo "After checking, share:"
echo "  - Which node failed (if any)"
echo "  - Any error messages shown"
echo "  - Screenshot of the execution (if possible)"
echo ""
