#!/bin/bash
# Guide to get n8n API key from UI
# Usage: bash scripts/get_n8n_api_key_guide.sh

echo "=========================================="
echo "Getting n8n API Key from UI"
echo "=========================================="
echo ""
echo "📍 Follow these steps:"
echo ""
echo "1. Make sure port forwarding is active:"
echo "   On Desktop PowerShell: .\connect-vast.ps1"
echo "   (Keep that window open!)"
echo ""
echo "2. Open n8n in your browser:"
echo "   http://localhost:5678"
echo ""
echo "3. Log in to n8n (if prompted)"
echo ""
echo "4. Go to: Settings → API (or Settings → API Keys)"
echo ""
echo "5. Create a new API key:"
echo "   - Click 'Create API Key' or 'Add API Key'"
echo "   - Give it a name (e.g., 'Auto Import')"
echo "   - Copy the API key that appears"
echo ""
echo "6. Once you have the API key, run this command:"
echo "   (On VAST Terminal)"
echo ""
echo "   echo 'N8N_API_KEY=your_api_key_here' >> ~/Nextwork-Teachers-TechMonkey/.env"
echo ""
echo "   OR edit .env manually:"
echo "   nano ~/Nextwork-Teachers-TechMonkey/.env"
echo "   (Add or update: N8N_API_KEY=your_api_key_here)"
echo ""
echo "7. Test the API key:"
echo "   (On VAST Terminal)"
echo ""
echo "   cd ~/Nextwork-Teachers-TechMonkey"
echo "   source .env"
echo "   curl -H \"X-N8N-API-KEY: \$N8N_API_KEY\" http://localhost:5678/api/v1/workflows"
echo ""
echo "   If you see JSON output (not 'unauthorized'), the key works!"
echo ""
echo "8. Then import workflows:"
echo "   (On VAST Terminal)"
echo ""
echo "   bash scripts/import_new_workflows.sh"
echo ""
echo "=========================================="
